import os

CELERY_BROKER_URL = os.environ.get('REDIS_CONNECTION_URL')

PROXY_STRING = os.environ.get('PROXY_STRING')

REDIS_HOST = os.environ.get('REDIS_HOST')

REDIS_PORT = os.environ.get('REDIS_PORT')

REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD')

REDIS_WORK_DB = int(os.environ.get('REDIS_WORK_DB', 1))

REDIS_KEYS_EXPIRE_TIME = int(os.environ.get('REDIS_KEYS_EXPIRE_TIME', 86400))

SCRAPER_MAX_REQUEST_RETRIES = int(os.environ.get('SCRAPER_MAX_REQUEST_RETRIES', 20))

IMAGES_DOWNLOADER_MAX_REQUEST_RETRIES = int(os.environ.get('IMAGES_DOWNLOADER_MAX_REQUEST_RETRIES', 10,))

MINIMUM_UNIQUENESS_COEFFICIENT = float(os.environ.get('MINIMUM_UNIQUENESS_COEFFICIENT', 0.92))

POST_MODERATION_FOLDER = os.environ.get('POST_MODERATION_FOLDER', 'post_moderation')
